# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/ansh/final_miniproject/final_miniproject.cache/wt [current_project]
set_property parent.project_path /home/ansh/final_miniproject/final_miniproject.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/ansh/final_miniproject/final_miniproject.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/ansh/Desktop/project_files/bet_regis.vhd
  /home/ansh/final_miniproject/final_miniproject.srcs/sources_1/new/sub_reg.vhd
  /home/ansh/Desktop/project_files/subtractor.vhd
  /home/ansh/Desktop/project_files/GameOver.vhd
  /home/ansh/Desktop/project_files/FSM_Delay.vhd
  /home/ansh/Desktop/project_files/feed_amount.vhd
  /home/ansh/Desktop/project_files/Decider.vhd
  /home/ansh/Desktop/project_files/comparator.vhd
  /home/ansh/Desktop/project_files/Bset_RNG.vhd
  /home/ansh/Desktop/project_files/Bet_On.vhd
  /home/ansh/Desktop/project_files/7_segement_display.vhd
  /home/ansh/Desktop/project_files/Seven_upSeven_down.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/ansh/Desktop/project_files/mini_pro.xdc
set_property used_in_implementation false [get_files /home/ansh/Desktop/project_files/mini_pro.xdc]


synth_design -top Seven_upSeven_down -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Seven_upSeven_down.dcp

catch { report_utilization -file Seven_upSeven_down_utilization_synth.rpt -pb Seven_upSeven_down_utilization_synth.pb }
